### ISSUE TITLE
关于程序调试 

### ISSUE THREAD

**Issue by lfb637** [zxgx/ccks20-dev#1]
你好，在调试您这份代码，遇到了：
Building prefix dict from the default dictionary ...
Loading model from cache C:\Users\lfb\AppData\Local\Temp\jieba.cache
Loading model cost 0.472 seconds.
Prefix dict has been built successfully.
Traceback (most recent call last):
  File "D:/py-workspace/ccks20-dev-master/src/entity_extractor.py", line 157, in <module>
    corpus = se.get_candidate_entity(corpus)
  File "D:/py-workspace/ccks20-dev-master/src/entity_extractor.py", line 46, in get_candidate_entity
    candidate_entities = self.extract_subject(entity_mention, subject_properties, question)
  File "D:/py-workspace/ccks20-dev-master/src/entity_extractor.py", line 91, in extract_subject
    relations = get_relations_2hop(entity)
  File "D:\py-workspace\ccks20-dev-master\src\kb_utils.py", line 9, in get_relations_2hop
    res = json.loads(gc.query('pkubase', 'json', sparql))
  File "D:\Anaconda3\lib\json\__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "D:\Anaconda3\lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "D:\Anaconda3\lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
我debug了跟着走了一遍，到这出现问题了，
![image](https://user-images.githubusercontent.com/32834651/159621522-f6fcb121-efee-40e8-a40e-b238b8c810f8.png)
尝试了没解决，请教以下

**Comment by zxgx** [comment]
从你的报错来看的话，建议检查一下GstoreConnector的连接，以及pkubase的数据是否有问题  
这是两年前的代码了，很多细节我也忘了，另外我当时参加了2020的比赛但是因为效果不行，所以也没获得名次，建议找下这几年获奖的队伍的论文和代码，不建议再跟进这份代码了
